### ISSUE TITLE
ATEM Constellation 8K output selection

### ISSUE THREAD

**Issue by vuzya** [Sofie-Automation/sofie-atem-connection#112]
* **I'm submitting a ...**
[X] question about how to use this project

* **Summary**
Hello. Guys, please advise - how do I select an output for ATEM Constellation 8K? It described having 24 independent outputs, but it's not clear which methods I have to use to select the program output target.

**Comment by Julusian** [comment]
In this project the outputs are called auxes (because they are named that in older models and the official sdk). So to route something to one of the outputs use the https://nrkno.github.io/tv-automation-atem-connection/classes/atem.html#setauxsource method or corresponding command.

The list of possible source ids, isnt very well documented here currently, but you can find a mostly complete list at https://atem.julusian.dev/enums
