### ISSUE TITLE
Feature Request: Add Counter Command

### ISSUE THREAD

**Issue by joelkohler** [Sofie-Automation/sofie-atem-connection#135]
Is it possible, to add a command to set the counter time, reset, start abd stop it?

**Comment by bevand10** [comment]
Hi Joel,

Could you clarify what you mean by Counter Time, and add a screen grab of the ATEM control app highlighting which time on that display you'd like to adjust please?

**Comment by joelkohler** [comment]
I mean the counter overlay for the new ATEM Constellation HD models.

![image](https://user-images.githubusercontent.com/47793291/213868994-f8c6422c-818c-4884-8c11-5b6bfc85e18e.png)

**Comment by bevand10** [comment]
Counter also described at https://heretorecord.com/blog/counter-overlay-on-the-atem-constellation-hd

**Comment by Julusian** [comment]
This looks like a relatively simple feature to support, but will most likely require someone to reverse engineer it. I don't expect any prior work on reverse engineering this

**Comment by bevand10** [comment]
And that reverse engineering person having hands-on access to that hardware device.

**Comment by Julusian** [comment]
This is supported in v3.2.0

It was nice to sit down and reverse engineer more of the api. Its been almost a year since I've had the chance to do that

> And that reverse engineering person having hands-on access to that hardware device.

With the right tooling, you don't always need access to the device to reverse engineer anything. I almost managed to do it all, but did use the real thing for figuring out the correct current time message as it would have been too much guesswork to figure out the command name otherwise.
