### ISSUE TITLE
incorrect parsing of ATEM data

### ISSUE THREAD

**Issue by nytamin** [Sofie-Automation/sofie-atem-connection#15]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Some strange data sent from my ATEM Television Studio causes the state to go bananas.

* **Other information**
Among others, this data is sent into MixEffectKeyFlyPropertiesGetCommand.deserialize():
Buffer(0x509be28400000000)
this creates
	this.mixEffect = 80
which in turn when calling state.video.getMe(this.mixEffect)
	creates ME[80], effectively making ME into a sparse array, causing problems further down the line

I'm appending a [wireshark trace,](https://we.tl/Y5vO7Dkzh9) there are some other trange data in there as well, causing the state.video.ME[] to become [ [Object], <72 empty items>, [Object], <6 empty items>, [Object], <26 empty items>, [Object] ]
on the indexes [ '0', '73', '80', '107' ]

**Comment by mint-dewit** [comment]
The current status on this is that we throw an error when we find incorrect data. On some models this can however be mildy annoying as there are many errors (Ex. #24)

The errors on the user side of the library do not mean the user can do anything against this, this is really an error on the atem side of the connection and we unfortunately are not in a position where we can improve that. For this reason I think we could change the error throwing behaviour to a warning emitter or a `parserError` emitter. This could be something used for debugging or even logging in production systems but would not be as annoying for library consumers working on models that emit a lot of errors.

**Comment by Julusian** [comment]
A prerelease of v2.0.0 has just been pushed to npm under the nightly tag `yarn add atem-connection@nightly` that should resolve this, along with other problems.
The parsing has been made a lot less picky on values to avoid errors like this, and any out of range ids are now debug warnings rather than errors.

We are happy that v2.0.0 should be stable, but want to spend a bit more time giving it some realistic testing before doing a proper release of it.
