### ISSUE TITLE
100% CPU usage because of invalid parameter

### ISSUE THREAD

**Issue by haakonnessjoen** [Sofie-Automation/sofie-atem-connection#37]
https://github.com/nrkno/tv-automation-atem-connection/blob/f35250d6eb46287d3295c27a772b4a8c17c09181/src/lib/atemSocketChild.ts#L57

Because of an invalid parameter to Nanotimer, the retransmit timer is called on *every tick*. This makes the spawed client process utilize 100% cpu on a core.

The reason is that the interval argument should have been '10m' not '10ms'.

**Comment by mint-dewit** [comment]
Well, the parameter is intentionally set to 10 ms, the atem needs a very fast retransmit if it doesn't acknowledge a packet, otherwise it starts to behave wonky.

I did not see this 100% CPU usage myself when testing this. I will investigate if I did something wrong in testing or if we should perhaps make this optional behaviour.

**Comment by Lange** [comment]
@baltedewit The problem is our syntax, not our intent:

`nanotimer`'s syntax for specifying "10 milliseconds" is indeed `10m`, as @haakonnessjoen stated:
![image](https://user-images.githubusercontent.com/873012/48984109-2381e280-f0bd-11e8-9c60-a799f837b49f.png)


`10ms` is invalid, and probably silently fails into a state where our interval runs as fast as possible.

**Comment by mint-dewit** [comment]
> The problem is our syntax, not our intent

Ohhh got it, I said nothing then.

**Comment by mint-dewit** [comment]
The problem is not the parameter, rather the way the nanotimer library deals with intervals. This is inherent to being able to deal with high accuracy timers in nodejs. The issue does not appear during stress testing but rather when we are not sending any commands, which explains why I didn't notice it before.

I think we can get away with the resending interval not being timed accurately, and luckily the timeouts for the ack'ing mechanism don't seem to suffer from the same issue.

**Comment by haakonnessjoen** [comment]
You just need to change the parameter from '10ms' to '10m'. You are using the nanotimer library wrong.

**Comment by mint-dewit** [comment]
> You just need to change the parameter from '10ms' to '10m'. 

Have done so and confirmed it does _not_ fix the 100% cpu issue. This is explained by the author here: https://github.com/Krb686/nanotimer/issues/3 We are removing the high accuracy interval timer as it is not 100% necessary anyway.
