### ISSUE TITLE
Several errors from 8.0.1 version on ATEM Production Studio 4K

### ISSUE THREAD

**Issue by Kohbrax** [Sofie-Automation/sofie-atem-connection#61]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
After updating the Atem to Version 8.0.1 we had several errors. A downgrade to version 7.5.2 is not working either. There are still he same errors. Seems that i has something to to with the missing DVE.

I modified the atemUtil.ts to output all errors. So there may be subsequent parsing errors.

```
Number too small -871665072 -1000000 1000000 (commands\MixEffects\Key\MixEffectKeyDVECommand.ts:97:20)

Number too big 1768187213 -1000000 1000000 (commands\MixEffects\Key\MixEffectKeyDVECommand.ts:98:20)

Number too big 1817190497 -332230 332230 (commands\MixEffects\Key\MixEffectKeyDVECommand.ts:99:19)

Value 101 is not a valid option in enum (DVEEffect Enum; MixEffectKeyDVECommand.ts)

Number too big 12832 0 1600 (commands\MixEffects\Key\MixEffectKeyDVECommand.ts:104:27)

Number too small -72 0 100 (commands\MixEffects\Key\MixEffectKeyDVECommand.ts:106:30)

Number too big 34305 0 1000 (commands\MixEffects\Key\MixEffectKeyDVECommand.ts:113:27)

Number too big 97 0 3 (commands\MixEffects\Key\MixEffectKeyFlyPropertiesGetCommand.ts:13:25)

Number too big 121 0 3 (commands\MixEffects\Key\MixEffectKeyFlyPropertiesGetCommand.ts:14:31)

Number too big 15 0 3 (commands\MixEffects\Key\MixEffectKeyFlyKeyframeGetCommand.ts:13:25)

Number too big 170 0 3 (commands\MixEffects\Key\MixEffectKeyFlyKeyframeGetCommand.ts:14:31)

Number too big 75 1 2 (commands\MixEffects\Key\MixEffectKeyFlyKeyframeGetCommand.ts:16:21)

Number too big 1296389120 -32768000 32768000 (commands\MixEffects\Key\MixEffectKeyFlyKeyframeGetCommand.ts:22:20)

Number too big 1869762592 -32768000 32768000 (commands\MixEffects\Key\MixEffectKeyFlyKeyframeGetCommand.ts:23:20)

Number too big 827159908 -332230 332230 (commands\MixEffects\Key\MixEffectKeyFlyKeyframeGetCommand.ts:24:19)

Number too small -28141 -9000 9000 (commands\MixEffects\Key\MixEffectKeyFlyKeyframeGetCommand.ts:42:18)

Number too big 21316 -9000 9000 (commands\MixEffects\Key\MixEffectKeyFlyKeyframeGetCommand.ts:43:21)
```

We have several ATEM 2 M/E Production Studio 4K devices where we can downgrade the firmware without any other issues. Then it is possible to use the Old 0.10.0 version.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Do you have any current version of the protocol? The skaarhoj documentation does not support the new 8.0.1 version. With these informations i could fix the issues.

**Comment by Julusian** [comment]
Is it just the Production Studio 4K that is not working in 8.0.1, with the 2ME 4K working fine?

This sounds a lot like the issues in #15 and #24. The problem is that the atem sends some commands filled with jibberish, and we don't have a great strategy to filter them out right now.

The easy 'fix' is to add an error handler to the connection, and to ignore these 'errors'. It is on my todo list to figure out a better way of handling these expected command errors, but I havent gotten around to it yet.

**Comment by Julusian** [comment]
As for protocol documentation, [this](https://github.com/LibAtem/LibAtem/tree/master/LibAtem/Commands) project of mine is the most complete implementation I am aware of, but that wont really help in this case due to the jibberish being sent because of the lack of a dve

**Comment by Kohbrax** [comment]
I really dont want to test an upgrade of our 2ME devices right now. We had it updated once (in early august, where the lib had not support for v8) and the downgrade worked. Before the update to 8 i had it on this library without any errors.

The other ATEMS are important for out production - thats why i cannot test it.

But thanks for the Link to the c# Project.

Can you give me an example how to catch these errors for a single connection? I havent seen any example for that.

Thanks for your fast response! :)

**Comment by Julusian** [comment]
> I really dont want to test an upgrade of our 2ME devices right now

Thats reasonable. I am running 8.0 on my original 2ME without issues currently. And those errors normally only occur when the device doesnt have a DVE, but it is possible there could be edge cases with certain DVE/fly key values if you are ever setting those.

Something as simple as this will log the error, but won't interrupt the connection:
```
myAtem.on('error', function(err) {
  console.log(err);
});
```

**Comment by Kohbrax** [comment]
> Something as simple as this will log the error, but won't interrupt the connection:

i was looking for this for ages! Thanks!

Sometimes i have the feeling, that the parsing of the tcp packets seems to have the wrong length. So its getting worse with the errors. But that is just a feeling - might not be right.

We had a problem, that we could not connect to the atem with the normal atem control software, after the atem-connection lib has connected. Just with this one small atem, and just in this weird case.

Is it maybe a valid fix to disable capabilities of parsing DVE Commands, when the ATEM does not have any?

Funfact: The 1 M/E Production Studio 4k is working fine..

**Comment by Julusian** [comment]
> Sometimes i have the feeling, that the parsing of the tcp packets seems to have the wrong length. So its getting worse with the errors.

That should only happen when the protocol changes, but we have some tests in place to try and avoid errors from things like that

> We had a problem, that we could not connect to the atem with the normal atem control software, after the atem-connection lib has connected. Just with this one small atem, and just in this weird case.

I have had that sometimes before. A restart of the atem usually solves it, but I have no idea why it happens, or if it is due to the library or something else.

> Is it maybe a valid fix to disable capabilities of parsing DVE Commands, when the ATEM does not have any?

That is something we are discussing. We have an idea on how to do that, so will hopefully be able to give it a try soon.

> Funfact: The 1 M/E Production Studio 4k is working fine..

That one has a DVE, so should be fine :)

**Comment by Julusian** [comment]
A prerelease of v2.0.0 has just been pushed to npm under the nightly tag `yarn add atem-connection@nightly` that should resolve this, along with other problems.
The parsing has been made a lot less picky on values to avoid errors like this, and any out of range ids are now debug warnings rather than errors.

We are happy that v2.0.0 should be stable, but want to spend a bit more time giving it some realistic testing before doing a proper release of it.

**Comment by Kohbrax** [comment]
Nice! Thanks for the Info. I'll update my staging system to this version.
